Adds Spiral geometry type to XODR Geometry
maliput/maliput_malidrive pull request #261
Opened 2024-01-02 13:37 UTC by francocipollone

# 🎉 New feature

Related to #260 

## Summary

From OpenDRIVE Format Specification 1.5: 
```
This record describes a spiral as part of the road’s reference line. For this type of spiral, the curvature
change between start and end of the element is linear.

In order to provide consistency between spiral evaluations of various implementations, users are
highly recommended to use identical algorithms, or, at least, algorithms with reasonable accuracy
within the applicable range (i.e. curvature, length of spiral etc.).

The theory of clothoids is described (for example) at
http://en.wikipedia.org/wiki/Euler_spiral
A library for computing clothoids can be downloaded at
http://www.opendrive.org/downloads/spiral.zip
```

![image](https://github.com/maliput/maliput_malidrive/assets/53065142/d8b17177-9a65-4ce0-9146-b770c15524e6)

## Checklist
- [x] Signed all commits for DCO
- [x] Added tests
- [ ] Added example and/or tutorial
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] Consider updating Python bindings (if it affects the public API)

2024-01-02 19:17 UTC, agalbachicar requested changes
LGTM modulo the required test coverage.

2024-01-02 19:17 UTC, agalbachicar commented on test/regression/xodr/geometry_test.cc
Can we add tests with negative curvatures?

2024-01-02 19:17 UTC, agalbachicar commented on test/regression/xodr/parser_test.cc
Can we add tests with negative curvatures?

2024-01-03 17:50 UTC, francocipollone commented on test/regression/xodr/parser_test.cc
Done

2024-01-03 17:50 UTC, francocipollone commented on test/regression/xodr/geometry_test.cc
Done

2024-01-04 10:01 UTC, agalbachicar approved these changes
LGTM

2024-01-04 10:02 UTC, merged