Flags spiral support.
maliput/maliput_malidrive pull request #279
Opened 2024-04-29 08:08 UTC by agalbachicar

# 🎉 New feature

Closes #278

## Summary

Changes the documentation status

## Test it

N/A

## Checklist
- [x] Signed all commits for DCO
- [ ] Added tests
- [ ] Added example and/or tutorial
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] Consider updating Python bindings (if it affects the public API)

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

2024-04-29 14:00 UTC, francocipollone requested changes

2024-04-29 14:00 UTC, francocipollone commented on src/maliput_malidrive/xodr/README.md
> +Road | PlanView | Spirals | :gree_circle:
```suggestion
Road | PlanView | Spirals | :green_circle:
```

2024-04-29 18:53 UTC, francocipollone approved these changes

2024-04-30 08:32 UTC, merged

2024-04-30 08:33 UTC, agalbachicar commented
Thank you @francocipollone